"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Pill } from "lucide-react";
import { findCofactor } from "@/lib/knowledge/cofactors";
import { useUIPreferences } from "@/lib/ui/preferencesStore";
import { CitationList } from "@/components/ui/CitationList";

/**
 * A small chip for a single cofactor name (as it appears in
 * `Enzyme.cofactors`). Hover/focus to reveal a citation-backed popover with
 * the cofactor's role and pubchem/chebi links. Falls back to a plain chip
 * when the cofactor is not in the SysDope knowledge base.
 */
export function CofactorChip({ label }: { label: string }) {
  const [hovered, setHovered] = useState(false);
  const showCitations = useUIPreferences((s) => s.showCitations);
  const entry = findCofactor(label);

  if (!entry) {
    return (
      <span className="rounded-full bg-zinc-800/60 px-2 py-0.5 text-[10px] text-zinc-200 ring-1 ring-zinc-700">
        {label}
      </span>
    );
  }

  return (
    <span
      className="relative inline-block"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      onFocus={() => setHovered(true)}
      onBlur={() => setHovered(false)}
    >
      <button
        type="button"
        className="inline-flex items-center gap-1 rounded-full bg-fuchsia-500/10 px-2 py-0.5 text-[10px] text-fuchsia-200 ring-1 ring-fuchsia-500/30 transition hover:bg-fuchsia-500/20"
      >
        <Pill className="size-2.5" />
        {label}
      </button>
      <AnimatePresence>
        {hovered && (
          <motion.div
            role="tooltip"
            initial={{ opacity: 0, y: -2 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -2 }}
            transition={{ duration: 0.12 }}
            className="absolute left-0 top-full z-50 mt-1 w-72 rounded-md border border-zinc-800 bg-zinc-950/95 p-2 text-[11px] shadow-xl backdrop-blur"
          >
            <p className="text-xs font-semibold text-zinc-100">{entry.name}</p>
            <p className="mt-1 leading-snug text-zinc-300">{entry.role}</p>
            {entry.regeneration && (
              <p className="mt-1 text-[10px] leading-snug text-zinc-400">
                <span className="text-zinc-500">Regenerated by:</span>{" "}
                {entry.regeneration}
              </p>
            )}
            {showCitations && (
              <div className="mt-2 border-t border-zinc-800 pt-1.5">
                <CitationList citations={entry.citations} />
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </span>
  );
}
