import type { Citation } from "@/types/citation";
import type { Enzyme } from "@/types/enzyme";
import {
  CITATION_RAT_STRIATAL_EC_DA_MICRODIALYSIS,
  CITATION_STRIATAL_DA_TRANSMISSION_REVIEW,
} from "@/lib/education/physiologicDisplay";

/** Qualitative literature anchors for aqueous dopamine oxidation (not calibrated kinetics). */
const DOPAMINE_AUTOXIDATION_CONTEXT_CITES: Citation[] = [
  {
    sourceName: "Journal of the Chemical Society, Perkin Transactions 2",
    sourceType: "paper",
    title:
      "Spontaneous autoxidation of dopamine: aqueous kinetics and O₂ involvement (context for non-enzymatic oxidation)",
    doi: "10.1039/P29950000259",
    url: "https://doi.org/10.1039/P29950000259",
    accessedAt: "2026-05-06",
    confidence: "high",
  },
  {
    sourceName: "Frontiers in Molecular Neuroscience",
    sourceType: "paper",
    title: "Dopamine autoxidation is controlled by acidic pH (mechanistic context)",
    doi: "10.3389/fnmol.2018.00467",
    url: "https://doi.org/10.3389/fnmol.2018.00467",
    accessedAt: "2026-05-06",
    confidence: "high",
  },
];

const ACC = "2026-05-06";

const uniprot = (id: string): Citation => ({
  sourceName: "UniProt",
  sourceType: "database",
  title: `UniProt ${id}`,
  url: `https://www.uniprot.org/uniprotkb/${id}/entry`,
  accessedAt: ACC,
  confidence: "high",
});

const pubchem = (cid: string, title: string): Citation => ({
  sourceName: "PubChem",
  sourceType: "database",
  title,
  url: `https://pubchem.ncbi.nlm.nih.gov/compound/${cid}`,
  accessedAt: ACC,
  confidence: "medium",
});

/** MedlinePlus Genetics — consumer-facing NIH overview. */
const medlineGenetics = (slug: string, title: string): Citation => ({
  sourceName: "MedlinePlus Genetics",
  sourceType: "government",
  title,
  url: `https://medlineplus.gov/genetics/condition/${slug}/`,
  accessedAt: ACC,
  confidence: "high",
});

type Pack = Pick<Enzyme, "educationalOverview" | "overviewCitations">;

const PACKS: Record<string, Pack> = {
  pah: {
    educationalOverview:
      "Phenylalanine hydroxylase (PAH) is the gateway enzyme that converts the essential amino acid L-phenylalanine into L-tyrosine using molecular oxygen and a tetrahydrobiopterin (BH4) cofactor plus non-heme iron. Without functional PAH, phenylalanine accumulates while tyrosine and downstream catecholamine precursors are constrained, which is the biochemical basis of phenylketonuria when the enzyme is absent or severely impaired.\n\n" +
      "Biochemically, PAH couples ring hydroxylation to cofactor oxidation (BH4 → BH2) and must be regenerated by separate enzymes not modeled in detail here; the simulator tracks BH4 pools only as a modulator of TH/PAH reactions. PAH expression is highest in hepatocytes in vivo, so the neuron-centric toy graph treats PAH as a generic upstream source block for teaching rather than a compartment-accurate liver model.\n\n" +
      "Therapeutically, phenylketonuria management centers on dietary phenylalanine restriction and, in responsive genotypes, BH4-responsive pharmacologic cofactor supplementation; enzyme substitution therapies have also entered clinical use for select patients. The drug and disease notes in this drawer are static illustrations—always defer to current guidelines and prescribing information.",
    overviewCitations: [uniprot("P00439"), medlineGenetics("phenylketonuria", "Phenylketonuria (PKU)")],
  },
  th: {
    educationalOverview:
      "Tyrosine 3-monooxygenase (TH) is the committed, rate-limiting enzyme for catecholamine biosynthesis: it installs the catechol ring on L-tyrosine to make L-DOPA using BH4, O2, and iron at the active site. Because TH gates flux into L-DOPA, most regulatory strategies that raise or lower dopamine synthesis in neurons target this step (activity state, phosphorylation in vivo, cofactor availability, and end-product feedback concepts).\n\n" +
      "TH requires sustained BH4 and iron availability; mitochondrial iron handling and GTP cyclohydrolase activity (BH4 synthesis) are clinically relevant upstream determinants in dopaminergic neurons. In the simulator, TH is intentionally the slowest vmax on the synthetic arm so boluses of tyrosine cannot bypass a pharmacologically inhibited TH.\n\n" +
      "Levodopa therapy bypasses TH by supplying L-DOPA directly in Parkinson disease, but peripheral metabolism and transport still matter; the pharmacology notes link PubChem identities only.",
    overviewCitations: [
      uniprot("P07101"),
      CITATION_STRIATAL_DA_TRANSMISSION_REVIEW,
      pubchem("6030", "Levodopa (PubChem)"),
    ],
  },
  ddc: {
    educationalOverview:
      "Aromatic L-amino-acid decarboxylase (DDC / AADC) decarboxylates L-DOPA to dopamine using pyridoxal 5′-phosphate (PLP) as an essential cofactor that stabilizes carbanionic intermediates during CO2 loss. This step is rapid compared with TH in most settings, so clinically relevant L-DOPA accumulation usually signals upstream TH limitation or very high exogenous L-DOPA input rather than DDC insufficiency.\n\n" +
      "DDC is expressed in both CNS and peripheral tissues; modern oral levodopa is almost always paired with a peripheral DDC inhibitor (for example carbidopa) to reduce extracerebral conversion and improve central delivery. The simulator keeps that distinction as a narrative only—transport across the blood–brain barrier is not mechanistically simulated.\n\n" +
      "Rare congenital AADC deficiency is a distinct pediatric neurometabolic disorder; do not confuse the educational sliders here with that diagnosis.",
    overviewCitations: [uniprot("P20711"), pubchem("2481", "Carbidopa (PubChem)")],
  },
  dbh: {
    educationalOverview:
      "Dopamine β-hydroxylase (DBH) converts dopamine to norepinephrine inside the synaptic vesicle using molecular oxygen and copper at the active site, with ascorbate as the obligate reductant that maintains the copper cycling required for two-electron chemistry. This step is what differentiates dopaminergic from noradrenergic terminals when vesicular packaging and release are considered together.\n\n" +
      "DBH deficiency states exist in humans (plasma DBH activity correlates with noradrenergic tone in some studies), but the toy model collapses adrenal and neuronal compartments. Ascorbate and copper pools are represented only as textual cofactors rather than explicit kinetic constraints.\n\n" +
      "Drugs that manipulate catecholamine tone (reuptake inhibitors, receptor antagonists) are not modeled as direct DBH inhibitors here.",
    overviewCitations: [uniprot("P09172")],
  },
  pnmt: {
    educationalOverview:
      "Phenylethanolamine N-methyltransferase (PNMT) transfers a methyl group from S-adenosyl-L-methionine (SAM) to norepinephrine to form epinephrine, producing S-adenosyl-L-homocysteine (SAH). PNMT is enriched in the adrenal medulla and a restricted set of brainstem nuclei in mammals, so epinephrine is largely an adrenal stress hormone while norepinephrine dominates sympathetic neurotransmission.\n\n" +
      "The simulator merges cytosolic pools for teaching; SAM consumption is tracked as a shared cofactor pool with COMT-driven O-methylation reactions.\n\n" +
      "Clinical modulation of PNMT itself is uncommon compared with receptor- or transporter-targeted drugs; the drawer’s medication notes are illustrative only.",
    overviewCitations: [uniprot("P11086")],
  },
  comt: {
    educationalOverview:
      "Catechol-O-methyltransferase (COMT) O-methylates catechol rings using SAM as methyl donor, terminating extracellular and some intracellular catecholamine signals and producing O-methylated metabolites (for example 3-MT from dopamine). A soluble (S-COMT) and membrane-bound (MB-COMT) repertoire exists in tissue; both reduce synaptic dwell time of dopamine alongside reuptake.\n\n" +
      "COMT pharmacology (entacapone, tolcapone) is used adjunctively with levodopa in Parkinson disease to prolong L-DOPA half-life by blocking peripheral and sometimes central O-methylation; tolcapone carries hepatotoxicity risk historically emphasized in labeling. The simulator encodes neither liver monitoring nor exact brain penetration—only a kinetic weight on COMT-catalyzed edges.\n\n" +
      "COMT Val158Met genotype affects human enzyme activity and has been studied in cognitive and pain phenotypes; that genetics layer is not simulated.",
    overviewCitations: [uniprot("P21964"), pubchem("52894", "Entacapone (PubChem)")],
  },
  mao_a: {
    educationalOverview:
      "Monoamine oxidase A (MAO-A) is a flavin-dependent outer mitochondrial membrane enzyme that oxidatively deaminates primary amines—including monoamine transmitters—to aldehydes with peroxide generation. In this toy graph MAO-A is wired heavily toward 3-MT and other extracellular catechol metabolites rather than bulk cytosolic dopamine clearance, which is dominated by MAO-B in the reactions shown.\n\n" +
      "MAO-A inhibition raises monoamine availability and is exploited therapeutically in some antidepressant strategies (with important dietary tyramine considerations for non-selective inhibitors). The simulator does not implement tyramine pressor risk or dietary interaction tables.\n\n" +
      "MAO-A and MAO-B overlap in substrate preference in vivo; the pathway split here is pedagogical.",
    overviewCitations: [uniprot("P21397")],
  },
  mao_b: {
    educationalOverview:
      "Monoamine oxidase B (MAO-B) oxidatively deaminates dopamine to DOPAL in astrocytes and neurons, feeding the aldehyde into aldehyde dehydrogenase pathways toward DOPAC and ultimately HVA. MAO-B-generated H2O2 contributes to oxidative load in tissue models; the relationship to pathology is debated and region-specific.\n\n" +
      "Selective MAO-B inhibitors (for example selegiline, rasagiline) are used in Parkinson disease partly to spare cytosolic dopamine when levodopa is co-administered; transdermal delivery routes differ in peripheral MAO-A exposure. The simulator collapses glia vs neuron compartments.\n\n" +
      "Non-enzymatic autoxidation of dopamine is represented separately as a schematic sink that competes when enzymatic clearance is pharmacologically weakened—see autoxidation citations.",
    overviewCitations: [uniprot("P27338"), ...DOPAMINE_AUTOXIDATION_CONTEXT_CITES],
  },
  aldh: {
    educationalOverview:
      "Aldehyde dehydrogenases (ALDH1A1/ALDH2 family members among others) oxidize DOPAL to DOPAC using NAD+ as hydride acceptor, preventing buildup of reactive aldehyde electrophiles. DOPAL is short-lived at steady state when MAO-B flux and ALDH capacity are balanced.\n\n" +
      "Disulfiram inhibits ALDH2 classically in alcohol-aversion therapy and illustrates how blocking downstream oxidation raises upstream aldehyde pools in principle. The simulator uses a single ALDH node for flux teaching.\n\n" +
      "Mitochondrial vs cytosolic isoform partitioning is not resolved here.",
    overviewCitations: [uniprot("P05091")],
  },
  tyr: {
    educationalOverview:
      "Tyrosinase is a copper-dependent enzyme that oxidizes L-tyrosine and L-DOPA toward dopaquinone on the melanin biosynthetic branch in melanocytes. Chemically related quinone chemistry can also arise from dopamine autoxidation in vitro, which is why dopamine oxidation appears in both enzymatic melanogenesis and ROS teaching tracks.\n\n" +
      "The simulator routes a lumped non-enzymatic dopamine sink toward dopaquinone-like pools for pedagogy; tyrosinase itself is not the same mechanism as aqueous autoxidation but shares conceptual quinone intermediates.\n\n" +
      "Tyrosinase inhibitors in dermatology (for example for hyperpigmentation) are outside the scope of this dopamine-focused toy graph.",
    overviewCitations: [uniprot("P14679")],
  },
  vmat2: {
    educationalOverview:
      "The vesicular monoamine transporter 2 (VMAT2; gene SLC18A2) packages cytosolic monoamines—including dopamine—into synaptic vesicles using the proton electrochemical gradient established by the vesicular ATPase. Sequestration lowers cytosolic dopamine exposure to mitochondrial MAO and is therefore neuroprotective in conceptual models, while also concentrating transmitter for quantal release.\n\n" +
      "VMAT2 has finite transport capacity; when cytosolic dopamine rises faster than packaging, overflow in the simulator triggers cytosolic alerts. Release is modeled as discrete quanta moving vesicular dopamine to the synaptic compartment.\n\n" +
      "VMAT2 depleters such as tetrabenazine reduce vesicular loading and are used in hyperkinetic movement disorders; reserpine is a historic VMAT inhibitor with broader monoamine depletion. These drug classes are named only illustratively with PubChem anchors—prescribing decisions require specialist oversight.",
    overviewCitations: [
      uniprot("Q05940"),
      CITATION_STRIATAL_DA_TRANSMISSION_REVIEW,
      pubchem("6014", "Tetrabenazine (PubChem)"),
    ],
  },
  dat: {
    educationalOverview:
      "The dopamine transporter (DAT; SLC6A3) clears synaptic dopamine back into the presynaptic terminal as a Na+/Cl−-coupled symport driven by ion gradients maintained by Na+/K+-ATPase. DAT kinetics set the temporal width of dopamine transients after release and shape occupancy at postsynaptic receptors.\n\n" +
      "Psychostimulants that block DAT (for example methylphenidate, amphetamine-class agents) increase extracellular dopamine and are used clinically in ADHD under controlled regimens; abuse liability relates to the same transporter. The simulator does not model behavior or reinforcement—only mass balance on edges.\n\n" +
      "DAT imaging ligands exist for research quantification of terminal density; no imaging is simulated.",
    overviewCitations: [
      uniprot("Q01959"),
      CITATION_STRIATAL_DA_TRANSMISSION_REVIEW,
      CITATION_RAT_STRIATAL_EC_DA_MICRODIALYSIS,
      pubchem("4158", "Methylphenidate (PubChem)"),
    ],
  },
  d1: {
    educationalOverview:
      "D1-like dopamine receptors (here DRD1) are Gs/olf-coupled receptors that elevate cAMP in spiny neurons and modulate corticostriatal plasticity. They work in parallel with D2-like pathways that often oppose motor and motivational tone at the circuit level.\n\n" +
      "The simulator represents receptor nodes as educational sinks that convert synaptic dopamine into abstract postsynaptic drive rather than literal second-messenger dynamics.\n\n" +
      "Fenoldopam is a peripheral D1 agonist used in hypertensive emergencies in humans; the pharmacology chip links PubChem for identity only.",
    overviewCitations: [uniprot("P21728"), pubchem("3346", "Fenoldopam (PubChem)")],
  },
  d2: {
    educationalOverview:
      "D2-class dopamine receptors (DRD2) are Gi/o-coupled and are the primary targets of many antipsychotics and of dopamine agonists used in Parkinson disease and restless legs syndrome. Presynaptic D2 autoreceptors additionally regulate synthesis and release in vivo.\n\n" +
      "The toy graph collapses autoreceptor feedback into a single homeostatic factor for each receptor node.\n\n" +
      "Haloperidol (typical D2 antagonist) and pramipexole (D2/D3 agonist) appear as static PubChem-linked examples only.",
    overviewCitations: [uniprot("P14416"), pubchem("3559", "Haloperidol (PubChem)"), pubchem("6077", "Pramipexole (PubChem)")],
  },
  d3: {
    educationalOverview:
      "DRD3 is enriched in limbic circuitry relative to motor striatum and has been pharmacologically targeted by agonists with high D3 affinity in research and therapeutics (for example pramipexole). Signaling bias and heteromerization complicate simple dose–response stories in real tissue.\n\n" +
      "SysDope does not resolve limbic vs motor geography—only a synaptic dopamine pool feeding abstract drive.\n\n" +
      "Impulse-control disorders reported with some dopamine agonists in Parkinson care are not modeled.",
    overviewCitations: [uniprot("P35462"), pubchem("6077", "Pramipexole (PubChem)")],
  },
  d4: {
    educationalOverview:
      "DRD4 has unusual pharmacology and genetic polymorphism (VNTR repeats) historically linked to novelty seeking in population genetics—effect sizes are small and replication mixed. Many atypical antipsychotics bind D4 among other monoamine receptors.\n\n" +
      "The educational node mirrors other receptors with a postsynaptic drive sink.\n\n" +
      "Clozapine is linked as a multi-target antipsychotic PubChem anchor.",
    overviewCitations: [uniprot("P21917"), pubchem("2818", "Clozapine (PubChem)")],
  },
  d5: {
    educationalOverview:
      "DRD5 is D1-like (Gs-coupled) and expressed at lower abundance than D1 in striatum in many species, but contributes to dopamine’s net excitatory influence in some projection neurons. It is not separately targeted by as many selective ligands as D2-class receptors.\n\n" +
      "The simulator treats D5 as parallel to D1 for teaching symmetry across receptor families.\n\n" +
      "Levodopa remains the backbone oral dopamine-replacement precursor in Parkinson disease; PubChem anchors the prodrug chemistry.",
    overviewCitations: [uniprot("P21918"), pubchem("6030", "Levodopa (PubChem)")],
  },
};

export function enzymeEducationalPick(
  id: string,
): Pick<Enzyme, "educationalOverview" | "overviewCitations"> {
  const p = PACKS[id];
  if (!p) return {};
  return {
    educationalOverview: p.educationalOverview,
    overviewCitations: p.overviewCitations,
  };
}
